# Posters for social events
[digital_meetup.meta]
template = "./templates/digital-meetup-poster.svg"

[digital_meetup]
instances = [
  {year = "2022", date = "April 6th", time = "7pm"},
  {year = "2022", date = "April 14th", time = "7pm"},
  {year = "2022", date = "April 20th", time = "7pm"},
  {year = "2022", date = "April 28th", time = "7pm"},
  {year = "2022", date = "May 4th", time = "7pm"},
]

[element_meetup.meta]
template = "./templates/element-meetup-poster.svg"

[element_meetup]
instances = [
  {year = "", date = "Every Thursday", time = "7pm"},
  {year = "2022", date = "May 19th", time = "7pm"},
  {year = "2022", date = "May 26th", time = "7pm"},
  {year = "2022", date = "June 2nd", time = "7pm"},
  {year = "2022", date = "June 9th", time = "7pm"},
  {year = "2022", date = "June 16th", time = "7pm"},
  {year = "2022", date = "June 23rd", time = "7pm"},
  {year = "2022", date = "June 30th", time = "7pm"},
  {year = "2022", date = "July 7th", time = "7pm"},
  {year = "2022", date = "July 14th", time = "7pm"},
  {year = "2022", date = "July 21th", time = "7pm"},
  {year = "2022", date = "July 28th", time = "7pm"},
]

