# Posters for social events
[digital_meetup.meta]
template = "./templates/digital-meetup-poster.svg"

[digital_meetup]
instances = [
  {year = "2022", date = "April 6th", time = "7pm"},
  {year = "2022", date = "April 14th", time = "7pm"},
  {year = "2022", date = "April 20th", time = "7pm"},
  {year = "2022", date = "April 28th", time = "7pm"},
  {year = "2022", date = "May 4th", time = "7pm"},
]
