# Posters for social events
[digital_meetup.meta]
template = "./templates/digital-meetup-poster.svg"

[digital_meetup]
instances = [
  {year = "2022", date = "April 6th", time = "7pm"},
  {year = "2022", date = "April 14th", time = "7pm"},
  {year = "2022", date = "April 20th", time = "7pm"},
  {year = "2022", date = "April 28th", time = "7pm"},
  {year = "2022", date = "May 4th", time = "7pm"},
]

[element_meetup.meta]
template = "./templates/element-meetup-poster.svg"

[element_meetup]
instances = [
  {year = "", date = "Every Thursday", time = "7pm"},
  {year = "2022", date = "May 19th", time = "7pm"},
  {year = "2022", date = "May 26th", time = "7pm"},
  {year = "2022", date = "June 2nd", time = "7pm"},
  {year = "2022", date = "June 9th", time = "7pm"},
  {year = "2022", date = "June 16th", time = "7pm"},
  {year = "2022", date = "June 23rd", time = "7pm"},
  {year = "2022", date = "June 30th", time = "7pm"},
  {year = "2022", date = "July 7th", time = "7pm"},
  {year = "2022", date = "July 14th", time = "7pm"},
  {year = "2022", date = "July 21th", time = "7pm"},
  {year = "2022", date = "July 28th", time = "7pm"},
  {year = "2022", date = "August 4th", time = "7pm"},
  {year = "2022", date = "August 11th", time = "7pm"},
  {year = "2022", date = "August 18th", time = "7pm"},
  {year = "2022", date = "August 25th", time = "7pm"},
  {year = "2022", date = "September 1st", time = "7pm"},
  {year = "2022", date = "September 22nd", time = "7pm"},
  {year = "2022", date = "September 29th", time = "7pm"},
  {year = "2022", date = "October 6th", time = "7pm"},
  {year = "2022", date = "October 13th", time = "7pm"},
  {year = "2022", date = "October 20th", time = "7pm"},
  {year = "2022", date = "October 27th", time = "7pm"},
  {year = "2022", date = "November 3rd", time = "7pm"},
  {year = "2022", date = "November 10th", time = "7pm"},
  {year = "2022", date = "November 17th", time = "7pm"},
  {year = "2022", date = "November 24th", time = "7pm"},
]

[qeii_meetup.meta]
template = "./templates/qeii-meetup-poster.svg"

[qeii_meetup]
instances = [
  {year = "", date = "Every Thursday", time = "7pm"},
  {year = "2023", date = "Feburary 9th", time = "7pm"},
  {year = "2023", date = "Feburary 16th", time = "7pm"},
  {year = "2023", date = "Feburary 23rd", time = "7pm"},
  {year = "2023", date = "March 2nd", time = "7pm"},
  {year = "2023", date = "March 9th", time = "7pm"},
  {year = "2023", date = "March 16th", time = "7pm"},
  {year = "2023", date = "March 23rd", time = "7pm"},
  {year = "2023", date = "March 30th", time = "7pm"},
  {year = "2023", date = "April 6th", time = "7pm"},
  {year = "2023", date = "April 13th", time = "7pm"},
  {year = "2023", date = "April 20th", time = "7pm"},
  {year = "2023", date = "April 27th", time = "7pm"},
  {year = "2023", date = "May 11th", time = "7pm"},
  {year = "2023", date = "May 18th", time = "7pm"},
  {year = "2023", date = "May 25th", time = "7pm"},
]
